sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 'node'
script:
  - npm run lint
  - CONTENT_HOST=https://static.clickcounter.hiv DOTHIV__DOMAIN=click4life.hiv DOTHIV__REDIRECT=https://dothiv.jimdo.com/ make -B build
  - echo static.clickcounter.hiv > build/CNAME
  - cd build
  - echo "machine github.com login travis-ci password ${GH_TOKEN}" > ~/.netrc
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git init
  - git add -A
  - git commit -m 'update build'
  - git remote add origin `git -C .. remote get-url origin`
  - git push -f origin master:gh-pages
