sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 'node'
script:
  - npm run lint
  - CONTENT_HOST=https://static.clickcounter.hiv DOTHIV__DOMAIN=click4life.hiv DOTHIV__REDIRECT=https://dothiv.jimdo.com/ make -B build
  - cd build
  - git init
  - git add -A
  - git commit -m 'update build'
  - git remote add origin `git -C .. remote get-url origin`
  - git push -f origin master:gh-pages
